PRutCun/Models/Trasporte.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PRutCun.Models
{
    public class Trasporte
    {
        [Key]
        public int PkTrasporte { get; set; }

        public string Nombre { get; set; }
        public string HoraInicial { get; set;}
        public string HoraFinal { get; set; }
        public string Dia { get; set; }
        public bool Estatus { get; set; }

        [ForeignKey ("Tipo")]
        public int? FkTipo { get; set; }
        public TipoTrasporte Tipo { get; set; }

    }
}

PRutCun/Controllers/TrasporteController.cs
using PRutCun.Controllers;
using PRutCun.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using PRutCun.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Data.SqlClient;
using Dapper;
using System.Data;

namespace PRutCun.Controllers
{
    public class TrasporteController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public TrasporteController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        SqlConnection connection = new SqlConnection("Data Source=DESKTOP-TBJQTNK; Initial Catalog=Rutcun; Integrated Security=True;");
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var response = await _context.ArticuloDb.ToListAsync();
            var response = await connection.QueryAsync<Transporte>("SpGetTrasporte", new { }, commandType: CommandType.StoredProcedure);
            return View(response);
        }
        [HttpGet]
        public IActionResult VistaCrear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Transporte i)
        {
            try
            {
                var response = await connection.QueryAsync<Transporte>("Sp_IngresarRuta", new { i.Nombre,i.HoraInicial,i.HoraFinal,i.Dia,i.Estatus,i.FkTipo }, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }
        [HttpGet]
        public IActionResult EditarTrasporte(int? id)
        {
            if (id == null)
            { return NotFound(); }
            var trasporte = _context.Trasporte.Find(id);
            if (trasporte == null)
            { return NotFound(); }

            return View(trasporte);
        }
        [HttpPost]
        public async Task<ActionResult> TrasporteEditar(Transporte request)
        {

            Transporte trasporte = new Transporte();
            trasporte = _context.Trasporte.Find(request.PkTransporte);
            if (trasporte != null)
            {

                await connection.QueryAsync<Transporte>("SpUpdateRuta", new { request.PkTransporte,request.Nombre,request.HoraInicial,request.HoraFinal,request.Dia,request.Estatus,request.FkTipo }, commandType: CommandType.StoredProcedure);

                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Transporte trasporte = new Transporte();
            trasporte.PkTransporte = id;
            return View(trasporte);
        }
        [HttpPost]
        public async Task<IActionResult> Borrar(Transporte i)
        {
            try
            {
                var response = await connection.QueryAsync<Transporte>("Sp_DeleteRuta", new { i.PkTransporte}, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }
    }
}

PRutCun/Controllers/UsuarioController.cs
using PRutCun.Controllers;
using PRutCun.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using PRutCun.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Data.SqlClient;
using Dapper;
using System.Data;
using System.Text;
using System.Security.Cryptography;

namespace PRutCun.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public UsuarioController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        SqlConnection connection = new SqlConnection("Data Source=DESKTOP-TBJQTNK; Initial Catalog=Rutcun; Integrated Security=True;");
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var response = await _context.ArticuloDb.ToListAsync();
            var response = await connection.QueryAsync<Usuario>("SpGetUsuarios", new { }, commandType: CommandType.StoredProcedure);
            return View(response);
        }
        [HttpGet]
        public IActionResult VistaCrear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Usuario i)
        {
            try
            {
                int RolPkRol = Convert.ToInt32(i.FkRol);
                string Password = Encrypt(i.Password);
                var response = await connection.QueryAsync<Usuario>("SpInsertUsuarios", new { i.Nombre, i.Nickname, Password, i.FkRol, RolPkRol }, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }
		[HttpGet]
		public IActionResult EditarUsuario(int? id)
		{
			if (id == null)
			{ return NotFound(); }
			var usuario = _context.Usuario.Find(id);
			if (usuario == null)
			{ return NotFound(); }

			return View(usuario);
		}
		[HttpPost]
		public async Task<ActionResult> UsuarioEditar(Usuario request)
		{

			Usuario usuario = new Usuario();
			usuario = _context.Usuario.Find(request.PkUser);
			if (usuario != null)
			{
				int RolPkRol = Convert.ToInt16(request.FkRol);
				await connection.QueryAsync<Usuario>("SpUpdateUsuario", new { request.PkUser, request.Nombre, request.Nickname,request.Password, request.FkRol,RolPkRol }, commandType: CommandType.StoredProcedure);

				return RedirectToAction(nameof(Index));
			}
			return NotFound();
		}
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Usuario usuario = new Usuario();
            usuario.PkUser = id;
            return View(usuario);
        }
        [HttpPost]
        public async Task<IActionResult> Borrar(Usuario i)
        {
            try
            {
                var response = await connection.QueryAsync<Usuario>("spDeleteUsuarios", new { i.PkUser }, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }

        public string Encrypt(String mensaje)
        {
            string hash = "Coding C";
            byte[] data = UTF8Encoding.UTF8.GetBytes(mensaje);

            MD5 md5 = MD5.Create();
            TripleDES tripledes = TripleDES.Create();

            tripledes.Key = md5.ComputeHash(UTF8Encoding.UTF8.GetBytes(hash));
            tripledes.Mode = CipherMode.ECB;

            ICryptoTransform transform = tripledes.CreateEncryptor();
            byte[] result = transform.TransformFinalBlock(data, 0, data.Length);

            return Convert.ToBase64String(result);
        }
    }
}

PRutCun/Views/Trasporte/EditarTrasporte.cshtml
@model PRutCun.Models.Transporte
@{
    ViewData["Title"] = "Transporte";
    Layout = "_LayoutCrud";
}

<div class="container-fluid">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h1 class="text-white"><strong>Editar</strong></h1>
            </div>

            <div class="card-body">

                <form asp-action="TrasporteEditar" method="post">
                    @*                    Id Del usuario oculto*@
                    <input type="hidden" asp-for="PkTransporte" />
                    <div class="form-group">
                        <label asp-for="Nombre">Ruta</label>
                        <input asp-for="Nombre" class="form-control" placeholder="ingresar nombre de la ruta" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="HoraInicial">HoraInicial</label>
                        <input asp-for="HoraInicial" class="form-control" placeholder="ingresar la hora inicial" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="HoraFinal">HoraFinal</label>
                        <input asp-for="HoraFinal" class="form-control" placeholder="ingresar la Hora Final" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dia">Dia</label>
                        <input asp-for="Dia" class="form-control" placeholder="ingresar los dias" required>

                    </div>
                    <div class="form-group">
                        <label asp-for="Estatus">Estatus</label>
                        <input asp-for="Estatus" class="form-control" placeholder="ingresar el estatus">

                    </div>
                    <div class="form-group">
                        <label asp-for="FkTipo">Tipo</label>
                        <input asp-for="FkTipo" class="form-control" placeholder="ingresar el Tipo de trasporte" required>

                    </div>

                    <div class="container-fluid">
                        <button type="submit" class="btn btn-success"><i class="fa-solid fa-feather"></i> Editar</button>
                    </div>
                </form>
                <br />
                <div class="container-fluid">
                    <a class="btn btn-outline-success" asp-controller="Trasporte" asp-action="Index"> Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>

PRutCun/Views/Trasporte/Eliminar.cshtml
@model PRutCun.Models.Transporte
@{
    ViewData["Title"] = "borrar trasporte";
    Layout = "_LayoutCrud";
}
@*@<h1>@ViewData["Title"]</h1>@*@


<div class="container-fluid">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h1 class="text-white"><strong>Borrar</strong></h1>
            </div>

            <div class="card-body">

                <form asp-action="Borrar" method="post">
                    @*                    @id del usuario oculto@
*@                    <input type="hidden" asp-for="PkTransporte" />
                    <h1><strong>Desea Borrar el transporte?</strong></h1>
                    <div class="container-fluid">
                        <a class="btn btn-danger" asp-controller="Trasporte" asp-action="Index">NO</a>
                        <button type="submit" class="btn btn-success">SI</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

PRutCun/Views/Trasporte/Index.cshtml
@model IEnumerable<PRutCun.Models.Transporte>
@{
    ViewData["Title"] = "Transporte";
    Layout = "_LayoutCrud";
}
<div>
    <div class="row">
        <div class="offset-9 col-3 mb-3">
            <a asp-action="VistaCrear" asp-controller="Trasporte" class="btn-success d-block mx-auto btn-lg"><i class="fa-solid fa-diamond"></i> Nuevo transporte </a>
        </div>
    </div>

    <div class="container-fluid">
        <div class="offset-12">
            <div class="card border">
                <div class="card-header bg-dark">
                    <h1 class="text-white"><strong>Lista de trasporte</strong></h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        @if (Model.Count() > 0)
                        {
                                <table class="table table-bordered" id="tblUsuarios" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.Nombre)
                                            </th>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.HoraInicial)
                                            </th>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.HoraFinal)
                                            </th>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.Dia)
                                            </th>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.Estatus)
                                            </th>
                                            <th>
                                            @Html.DisplayNameFor(x=>x.FkTipo)
                                            </th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach (var iteam in Model)
                                    {
                                       <tr>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.Nombre)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.HoraInicial)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.HoraFinal)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.Dia)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.Estatus)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x=>iteam.FkTipo)
                                            </td>
                                            <td>
                                                    <a class="btn btn-warning" asp-action="EditarTrasporte" asp-route-id="@iteam.PkTransporte "><i class="fa-solid fa-pen-nib"></i>Editar </a>
                                                    <a class="btn btn-danger" asp-action="Eliminar" asp-route-id="@iteam.PkTransporte"><i class="fa-solid fa-poo"></i>Eliminar </a>
                                            </td>
                                       </tr>
                                    }
                                    </tbody>
                                </table>
                        }
                        else
                        {
                                <p>No hay registro</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PRutCun/Views/Trasporte/VistaCrear.cshtml
@model PRutCun.Models.Transporte
@{
    ViewData["Title"] = "crear Transporte";
    Layout = "_LayoutCrud";
}
@*<h1>@ViewData["Title"]</h1>*@


<div class="container-fluid">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h1 class="text-white"><strong>Nuevo trasporte</strong></h1>
            </div>

            <div class="card-body">

                <form asp-action="Crear" method="post">
                    <div class="form-group">
                        <label asp-for="Nombre">Ruta</label>
                        <input asp-for="Nombre" class="form-control" placeholder="ingresar nombre de la ruta" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="HoraInicial">HoraInicial</label>
                        <input asp-for="HoraInicial" class="form-control" placeholder="ingresar la hora inicial" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="HoraFinal">HoraFinal</label>
                        <input asp-for="HoraFinal" class="form-control" placeholder="ingresar la Hora Final" required>
                    </div>
                    <div class="form-group">
                        <label asp-for="Dia">Dia</label>
                        <input asp-for="Dia" class="form-control" placeholder="ingresar los dias" required>
                        
                    </div>
                    <div class="form-group">
                        <label asp-for="Estatus">Estatus</label>
                        <input asp-for="Estatus" class="form-control" placeholder="ingresar el estatus" >

                    </div>
                    <div class="form-group">
                        <label asp-for="FkTipo">Tipo</label>
                        <input asp-for="FkTipo" class="form-control" placeholder="ingresar el Tipo de trasporte" required>

                    </div>
                    <div class="container-fluid">
                        <button type="submit" class="btn btn-success"><i class="fa-solid fa-feather"></i> Crear</button>
                    </div>
                </form>
                <br />
                <div class="container-fluid">
                    <a class="btn btn-outline-success" asp-controller="Usuario" asp-action="Index"> Volver</a>
                </div>
            </div>
        </div>
    </div>
</div>