PRutCun/Controllers/AyudaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PRutCun.Controllers
{
    public class AyudaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PRutCun/Controllers/ContacController.cs
using Microsoft.AspNetCore.Mvc;

namespace PRutCun.Controllers
{
    public class ContacController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PRutCun/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PRutCun.Context;
using PRutCun.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using System.Security.Cryptography;

namespace PRutCun.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _context;//va con guion bajo por que es una variable privada
        public LoginController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult LoginUser(string user, string password)
        {
            try
            {   
                string contraseñaTemp = Encrypt(password);
                string contraseña = Decrypt(contraseñaTemp);
                var response = _context.Usuario.Include(u => u.Rol).FirstOrDefault(x => x.Nickname == user && x.Password == contraseñaTemp);
                if (response != null)
                { 
                    if (response.Rol.PkRol == 1)
                    {
                        return Json(new { Success = true, Admin = true });
                    }
                    return Json(new { Success = true, Admin = false });
                }
                else
                {
                    return Json(new { Success = false, Admin = false });
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Surgio un error: " + ex.Message);
            }
        }

        public string Encrypt(String mensaje)
        {
            string hash = "Coding C";
            byte[] data = UTF8Encoding.UTF8.GetBytes(mensaje);

            MD5 md5 = MD5.Create();
            TripleDES tripledes = TripleDES.Create();

            tripledes.Key = md5.ComputeHash(UTF8Encoding.UTF8.GetBytes(hash));
            tripledes.Mode = CipherMode.ECB;

            ICryptoTransform transform = tripledes.CreateEncryptor();
            byte[] result = transform.TransformFinalBlock(data, 0, data.Length);

            return Convert.ToBase64String(result);
        }

        public string Decrypt(string MensajeEn)
        {
            string hash = "Coding C";
            byte[] data = Convert.FromBase64String(MensajeEn);

            MD5 md5 = MD5.Create();
            TripleDES tripledes = TripleDES.Create();

            tripledes.Key = md5.ComputeHash(UTF8Encoding.UTF8.GetBytes(hash));
            tripledes.Mode = CipherMode.ECB;

            ICryptoTransform transform = tripledes.CreateDecryptor();
            byte[] result = transform.TransformFinalBlock(data, 0, data.Length);

            return UTF8Encoding.UTF8.GetString(result);
        }
    }
}

PRutCun/Controllers/MapasController.cs
using PRutCun.Controllers;
using PRutCun.Context;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using PRutCun.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Data.SqlClient;
using Dapper;
using System.Data;

namespace PRutCun.Controllers
{
    public class MapasController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public MapasController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        SqlConnection connection = new SqlConnection("Data Source=DESKTOP-TBJQTNK; Initial Catalog=Rutcun; Integrated Security=True;");
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //var response = await _context.ArticuloDb.ToListAsync();
            var response = await connection.QueryAsync<Mapas>("SpGetMapas", new { }, commandType: CommandType.StoredProcedure);
            return View(response);
        }
        [HttpGet]
        public IActionResult VistaCrear()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Crear(Mapas i)
        {
            try
            {
                var response = await connection.QueryAsync<Mapas>("SpInsertMapas", new { i.MapaUrl,i.Fktransportes}, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }
        [HttpGet]
        public IActionResult EditarMapas(int? id)
        {
            if (id == null)
            { return NotFound(); }
            var mapas = _context.Mapas.Find(id);
            if (mapas == null)
            { return NotFound(); }

            return View(mapas);
        }
        [HttpPost]
        public async Task<ActionResult> MapasEditar(Mapas request)
        {

            Mapas mapas = new Mapas();
            mapas = _context.Mapas.Find(request.PkMapas);
            if (mapas != null)
            {
              
                await connection.QueryAsync<Mapas>("SpUpdateMapas", new { request.PkMapas,request.MapaUrl,request.Fktransportes}, commandType: CommandType.StoredProcedure);

                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            Mapas mapas = new Mapas();
            mapas.PkMapas= id;
            return View(mapas);
        }
        [HttpPost]
        public async Task<IActionResult> Borrar(Mapas i)
        {
            try
            {
                var response = await connection.QueryAsync<Mapas>("SpDeleteMapas", new { i.PkMapas }, commandType: CommandType.StoredProcedure); ;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                throw new Exception("surgio un error " + ex.Message);
            }
        }
    }
}

PRutCun/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRutCun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Estilo.css" />
    @*    <link rel="stylesheet" href="~/css/site.css" />
    *@
    <link rel="stylesheet" href="~/css/style.css" />
@*    Para el login
*@    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PRutCun/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRutCun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Estilo.css" />
    <crossorigin ="anonymous">
        <script src="https://kit.fontawesome.com/aff71718e3.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800,900" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <header>
        <div class="contenedor__nav">
            <nav>
                <img src="~/imagenes/pngegg.jpeg" class="logo">
                <a class="apartados" asp-controller="Inicio" asp-action="Index">
                    <i class="fa-sharp fa-solid fa-bus-simple"></i> INICIO
                </a>
                <a class="apartados" asp-action="Index" asp-controller="Contac">
                    <i class="fa-sharp fa-solid fa-users"></i> Contactanos
                </a>
                <a class="apartados" asp-action="Index" asp-controller="Ayuda">
                    <i class="fa-sharp fa-solid fa-lightbulb"></i> Ayuda
                </a>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <a asp-controller="Home" asp-action="Index">><button><input type="submit" value="Volver"></button></a>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer">
            <div class="contain">
                <div class="col">
                    <h1>Institucion</h1>
                    <ul>
                        <li><a target="_blank" href="https://upqroo.edu.mx/">UPQROO</a></li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Creditos</h1>
                    <ul>
                        <li>Carrera Rivas Crystyan Adamir</li>
                        <li>Martin Martines Arias</li>
                        <li>Axel Francisco Braga Dzul </li>
                        <li>Bryan Antonio Rodríguez López</li>
                        <li>Lopez Diaz Brandon</li>

                        <li>Alejandro Yahir Chi Chi </li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Agradecimientos</h1>
                    <ul>
                        <li>Maria Jose Sosa</li>
                        <li>Moisés Ortega zetina </li>
                        <li>Manuel Alejandro Flores Barrera</li>
                        <li>Alejandra Escalera </li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Ayuda</h1>
                    <ul>
                        <li>
                            <atarget ="_blank" href="ayuda.html"> Pagina de guia
                        </li>
                        <li>rutcunoficial@gmail.com</li>
                    </ul>
                </div>
                <div class="col social">
                    <h1>Redes sociales</h1>
                    <ul>
                        <li>
                            <a target="_blank" href="https://es-la.facebook.com/upqroo/">
                                <img src="https://www.facebook.com/images/fb_icon_325x325.png" width="32"
                                     style="width: 32px;"></img>
                            </a>
                        </li>
                        <li>
                            <a target="_blank"
                               href="https://twitter.com/UPQROO?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/1200px-Twitter-logo.svg.png"
                                     width="32" style="width: 32px;"></img>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://www.instagram.com/up_qroo/">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg"
                                     width="32" style="width: 32px;"></img>
                            </a>
                        </li>
                    </ul>
                    <a asp-action="Index" asp-controller="Login"><button>Admin Login</button></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

</html>

PRutCun/Views/Shared/_LayoutCrud.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRutCun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/aff71718e3.js" crossorigin="anonymous"></script>
    <crossorigin ="anonymous">
        <script src="https://kit.fontawesome.com/aff71718e3.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,800,900" rel="stylesheet">

    <link rel="stylesheet" href="~/css/sitecrud.css" />   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/06f80f73dc.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <script src="https://kit.fontawesome.com/cc69f106cf.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-3 mt-4">
                <a class="list-group-item list-group-item-action py-2 ripple" aria-current="true" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-bus-simple"></i><span>Rutcun</span></a>
                <a class="list-group-item list-group-item-action py-2 ripple" asp-controller="Mapas" asp-action="Index"><i class="fa-solid fa-map-location-dot"></i><span>Mapas</span></a>
                <a class="list-group-item list-group-item-action py-2 ripple" asp-controller="Trasporte" asp-action="Index"><i class="fa-solid fa-bus"></i><span>Transporte</span></a>
                <a class="list-group-item list-group-item-action py-2 ripple" asp-controller="Usuario" asp-action="Index"><i class="fa-solid fa-user"></i><span>Usuario</span></a>
                <a class="list-group-item list-group-item-action py-2 ripple" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-right-from-bracket"></i><span>Salir</span></a>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PRutCun/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRutCun</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/Inicio.css" />
    <link rel="stylesheet" href="~/css/Ayuda.css" />
    <crossorigin ="anonymous">
        <script src="https://kit.fontawesome.com/aff71718e3.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Poppins:400,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800,900" rel="stylesheet">
</head>
<body>
   <header>
    <div class="contenedor__nav">
        <nav>
            <img src="~/imagenes/pngegg.jpeg" class="logo">
            <a class="apartados" asp-controller="Inicio" asp-action="Index">
                <i class="fa-sharp fa-solid fa-bus-simple"></i> INICIO
            </a>
            <a class="apartados" asp-action="Index" asp-controller="Contac">
                <i class="fa-sharp fa-solid fa-users"></i> Contactanos
            </a>
                <a class="apartados" asp-action="Index" asp-controller="Ayuda">
                <i class="fa-sharp fa-solid fa-lightbulb"></i> Ayuda</a>
        </nav>
    </div>
</header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer">
            <div class="contain">
                <div class="col">
                    <h1>Institucion</h1>
                    <ul>
                        <li><a target="_blank" href="https://upqroo.edu.mx/">UPQROO</a></li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Creditos</h1>
                    <ul>
                        <li>Carrera Rivas Crystyan Adamir</li>
                        <li>Martin Martines Arias</li>
                        <li>Axel Francisco Braga Dzul </li>
                        <li>Bryan Antonio Rodríguez López</li>
                        <li>Lopez Diaz Brandon</li>

                        <li>Alejandro Yahir Chi Chi </li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Agradecimientos</h1>
                    <ul>
                        <li>Maria Jose Sosa</li>
                        <li>Moisés Ortega zetina </li>
                        <li>Manuel Alejandro Flores Barrera</li>
                        <li>Alejandra Escalera </li>
                    </ul>
                </div>
                <div class="col">
                    <h1>Ayuda</h1>
                    <ul>
                        <li>
                            <atarget ="_blank" href="ayuda.html"> Pagina de guia
                        </li>
                        <li>rutcunoficial@gmail.com</li>
                    </ul>
                </div>
                <div class="col social">
                    <h1>Redes sociales</h1>
                    <ul>
                        <li>
                            <a target="_blank" href="https://es-la.facebook.com/upqroo/">
                                <img src="https://www.facebook.com/images/fb_icon_325x325.png" width="32"
                                     style="width: 32px;"></img>
                            </a>
                        </li>
                        <li>
                            <a target="_blank"
                               href="https://twitter.com/UPQROO?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/1200px-Twitter-logo.svg.png"
                                     width="32" style="width: 32px;"></img>
                            </a>
                        </li>
                        <li>
                            <a target="_blank" href="https://www.instagram.com/up_qroo/">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg"
                                     width="32" style="width: 32px;"></img>
                            </a>
                        </li>
                    </ul>
                    <a asp-action="Index" asp-controller="Login"><button class="button">Admin Login</button></a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>